# 1. Create a 3x3x3 array with random values 

In [5]:
import numpy as np
np.random.random((3,3))

array([[0.79647136, 0.36379883, 0.60913408],
       [0.79906574, 0.34430421, 0.73471346],
       [0.93911047, 0.90341763, 0.09466535]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [29]:
import numpy as np
a=np.roll(np.diag(np.array([0,1,2,3,4])),-1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [61]:
import numpy as np
checkboard=np.zeros((8,8),dtype=int)
checkboard[0:8:2,0:8:2]=1
checkboard[1:8:2,1:8:2]=1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [72]:
import numpy as np
norm_matrix=np.random.random((5,5))
print(norm_matrix)
norm_min,norm_max=norm_matrix.min(),norm_matrix.max()
norm_matrix = (norm_matrix - norm_min)/(norm_max - norm_min)
print(norm_matrix)

[[0.98951802 0.56606222 0.43785848 0.10179133 0.05273498]
 [0.57661291 0.46878551 0.75807558 0.0681005  0.28436612]
 [0.83285666 0.69338725 0.97943813 0.24938297 0.26951181]
 [0.61439489 0.46102794 0.58364119 0.2315007  0.67945563]
 [0.14200314 0.74943063 0.02071559 0.75570943 0.0702529 ]]
[[1.         0.56290799 0.43057581 0.08368655 0.03305048]
 [0.57379844 0.46249875 0.7611046  0.04891081 0.27214066]
 [0.8382938  0.69433317 0.98959551 0.23603097 0.25680801]
 [0.61279708 0.45449137 0.58105304 0.21757285 0.67995292]
 [0.12519327 0.75218127 0.         0.75866226 0.05113252]]


# 5.  How to find common values between two arrays?

In [81]:
import numpy as np
onearr1=np.array([1,2,3,4,5,6])
onearr2=np.array([2,5,6,7,8,9])
print(np.intersect1d(onearr1,onearr2))

twoarr1=np.array([[1,2,3,4],[4,5,6,7]])
twoarr2=np.array([[4,9,10,11],[1,5,6,7]])
print(np.intersect1d(twoarr1,twoarr2))

[2 5 6]
[1 4 5 6 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [86]:
import numpy as np
print("Yesterday :" , np.datetime64('today','D')-np.timedelta64(1,'D'))
print("Today :" , np.datetime64('today','D'))
print("Tomorrow :" , np.datetime64('today','D')+np.timedelta64(1,'D'))

Yesterday : 2020-07-27
Today : 2020-07-28
Tomorrow : 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [113]:
import numpy as np
aran1=np.random.random((10))
aran2=np.random.random((10))
print(aran1)
print(aran2)

if np.allclose(aran1,aran2):
    print("Arrays are equal")
else:
    print("Arrays are not equal")
    

[0.03259022 0.70761801 0.04640112 0.728658   0.29930171 0.55165505
 0.21045091 0.3582763  0.29723673 0.10119825]
[0.69265938 0.56214181 0.92735403 0.22855784 0.69292157 0.26114139
 0.18286596 0.84855352 0.61724686 0.09618952]
Arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 


In [110]:
import numpy as np
arr10=np.random.random(10)
print("Original Vector\n",arr10)
arr10[arr10.argmax()]=0
print("Modified Vector\n",arr10)

Original Vector
 [0.56691905 0.63021821 0.61833601 0.62136235 0.07702405 0.23774669
 0.32588029 0.76442506 0.86812731 0.370731  ]
Modified Vector
 [0.56691905 0.63021821 0.61833601 0.62136235 0.07702405 0.23774669
 0.32588029 0.76442506 0.         0.370731  ]


# 9. How to print all the values of an array?

In [117]:
import numpy as np
np.set_printoptions(threshold=np.inf)
arrpr=np.zeros((5,5))
print(arrpr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [137]:
import numpy as np
subarr1=np.random.random((4,3))
print("Original Matrix: ",subarr1)
print("\n")


print("Subtracted Matrix: ", subarr1-subarr1.mean(axis=1,keepdims=True))


Original Matrix:  [[0.9228448  0.43988465 0.38041331]
 [0.86449183 0.9407291  0.19961288]
 [0.93649341 0.50887386 0.87586905]
 [0.88467608 0.42931407 0.12472289]]


Subtracted Matrix:  [[ 0.34179721 -0.14116294 -0.20063428]
 [ 0.19621389  0.27245116 -0.46866505]
 [ 0.16274797 -0.26487158  0.10212361]
 [ 0.40510507 -0.05025695 -0.35484812]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [188]:
import numpy as np

vec1=np.ones(10)
vec2=np.random.randint(0,len(vec1),10)
print("Original Vector is :",vec2)
print("Original Vector increased by 1 is :",vec1+vec2)


Original Vector is : [1 7 4 9 3 1 2 5 5 4]
Original Vector increased by 1 is : [ 2.  8.  5. 10.  4.  2.  3.  6.  6.  5.]


# 12.How to get the diagonal of a dot product?

In [141]:
import numpy as np
dotarr1=np.random.random((3,3))
dotarr2=np.random.random((3,3))
print("Array1 :",dotarr1,"\n")
print("Array2 :",dotarr2,"\n")
print("Dot Product :",np.dot(dotarr1,dotarr2),"\n")
print("Diagonal of Dot Product: ",np.diag(np.dot(dotarr1,dotarr2)),"\n")

Array1 : [[0.95688631 0.80996799 0.66004142]
 [0.71923496 0.45978225 0.19780403]
 [0.77262899 0.50823088 0.21635744]] 

Array2 : [[0.68985249 0.12867522 0.53746055]
 [0.04847473 0.72120857 0.80396119]
 [0.59817283 0.97049939 0.72872132]] 

Dot Product : [[1.09419224 1.34785321 1.64645773]
 [0.63677485 0.61611531 0.90035152]
 [0.68705553 0.67593343 0.98151978]] 

Diagonal of Dot Product:  [1.09419224 0.61611531 0.98151978] 



# 13.How to find the most frequent value in an array?

In [155]:
import numpy as np
from scipy import stats
freqarr=np.array([1,2,3,9,4,5,6,7,8,9,2,3,4,4,4,9,9,9,9,9,4,4,4])
print("The most frequent value in the array is :",stats.mode(freqarr)[0])

The most frequent value in the array is : [4]


# 14.How to get the n largest values of an array

In [160]:
import numpy as np

maxarr=np.array([1,2,3,9,4,5,6,7,8,9,2,3,4,4,4,9,9,9,9,9,4,4,4])
print("The max value in the array is :",np.max(maxarr))


The max value in the array is : 9


# 15.How to create a record array from a regular array?

In [170]:
import numpy as np
namearr=np.array(['Nancy','Herculus','Sherlock'])
print("First Name Array is :", namearr,"\n")
surnamearr=np.array(['Drew','Poirot','Holmes'])
print("SurName Array is :", surnamearr,"\n")
agearr=np.array(['18','12','28'])
print("Age Array is :", agearr,"\n")
result= np.core.records.fromarrays([namearr, surnamearr, agearr],names='detective1,detective2,detective3')
print("Record Array is: ",result)

First Name Array is : ['Nancy' 'Herculus' 'Sherlock'] 

SurName Array is : ['Drew' 'Poirot' 'Holmes'] 

Age Array is : ['18' '12' '28'] 

Record Array is:  [('Nancy', 'Drew', '18') ('Herculus', 'Poirot', '12')
 ('Sherlock', 'Holmes', '28')]
